package com.eslam.task.Model.UnitModel

import com.eslam.task.Model.UnitModel.Attachments
import com.google.gson.annotations.SerializedName
import java.io.Serializable

data class Data (

	@SerializedName("id") val id : Int,
	@SerializedName("user_id") val user_id : Int,
	@SerializedName("title") val title : String,
	@SerializedName("description") val description : String,
	@SerializedName("type") val type : Int,
	@SerializedName("title_type") val title_type : String,
	@SerializedName("child_type") val child_type : String,
	@SerializedName("allow_childrens") val allow_childrens : Int,
	@SerializedName("allow_infants") val allow_infants : Int,
	@SerializedName("allow_animals") val allow_animals : Int,
	@SerializedName("allow_extra") val allow_extra : Int,
	@SerializedName("guests") val guests : Int,
	@SerializedName("rooms") val rooms : Int,
	@SerializedName("beds") val beds : Int,
	@SerializedName("bathrooms") val bathrooms : Int,
	@SerializedName("balacons") val balacons : Int,
	@SerializedName("min_guests") val min_guests : Int,
	@SerializedName("max_childrens") val max_childrens : Int,
	@SerializedName("max_extra") val max_extra : Int,
	@SerializedName("min_days") val min_days : Int,
	@SerializedName("max_days") val max_days : Int,
	@SerializedName("longitude") val longitude : Double,
	@SerializedName("latitude") val latitude : Double,
	@SerializedName("country") val country : Int,
	@SerializedName("government") val government : Int,
	@SerializedName("city") val city : Int,
	@SerializedName("area") val area : String,
	@SerializedName("address") val address : String,
	@SerializedName("building_number") val building_number : String,
	@SerializedName("unit_number") val unit_number : String,
	@SerializedName("floor_number") val floor_number : String,
	@SerializedName("zipcode") val zipcode : Int,
	@SerializedName("bank_account") val bank_account : String,
	@SerializedName("bank_number") val bank_number : String,
	@SerializedName("fee") val fee : Int,
	@SerializedName("fee_static") val fee_static : Int,
	@SerializedName("vat") val vat : Int,
	@SerializedName("tourism") val tourism : Int,
	@SerializedName("tourism_static") val tourism_static : Int,
	@SerializedName("checkin") val checkin : String,
	@SerializedName("checkout") val checkout : String,
	@SerializedName("deliver_keys") val deliver_deliver_keyss : String,
	@SerializedName("get_keys") val get_get_keyss : String,
	@SerializedName("notes") val notes : String,
	@SerializedName("contract_image") val contract_image : String,
	@SerializedName("video") val video : String,
	@SerializedName("cancle_policy") val cancle_policy : Int,
	@SerializedName("status") val status : Int,
	@SerializedName("featured") val featured : Int,
	@SerializedName("currency") val currency : String,
	@SerializedName("price") val price : Int,
	@SerializedName("rate_count") val rate_count : Int,
	@SerializedName("rate_score") val rate_score : Int,
	@SerializedName("created_at") val created_at : String,
	@SerializedName("updated_at") val updated_at : String,
	@SerializedName("booking_count") val booking_count : Int,
	@SerializedName("attachments") val attachments : List<Attachments>
) : Serializable